# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Basketball

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Salary(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 20

    # Salary
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Salary
    def Sal(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + i * 4)) for i in range(self.SalLength())]
        elif j >= 0 and j < self.SalLength():
            return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + j * 4))
        else:
            return None

    # Salary
    def SalAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Float32Flags, self._tab.Pos + 0, self.SalLength())

    # Salary
    def SalLength(self):
        return 5

    # Salary
    def SalIsNone(self):
        return False


def CreateSalary(builder, sal):
    builder.Prep(4, 20)
    for _idx0 in range(5 , 0, -1):
        builder.PrependFloat32(sal[_idx0-1])
    return builder.Offset()
