# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Torch

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Parameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Parameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Parameters
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Parameters
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Parameters
    def Tensor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Torch.Tensor import Tensor
            obj = Tensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ParametersStart(builder):
    builder.StartObject(2)

def Start(builder):
    ParametersStart(builder)

def ParametersAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ParametersAddName(builder, name)

def ParametersAddTensor(builder, tensor):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(tensor), 0)

def AddTensor(builder, tensor):
    ParametersAddTensor(builder, tensor)

def ParametersEnd(builder):
    return builder.EndObject()

def End(builder):
    return ParametersEnd(builder)
